[2023-10-10 12:18:47,013] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ETL_toll_data.extract_data_from_csv manual__2023-10-10T12:13:42.528919+00:00 [queued]>
[2023-10-10 12:18:47,025] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ETL_toll_data.extract_data_from_csv manual__2023-10-10T12:13:42.528919+00:00 [queued]>
[2023-10-10 12:18:47,025] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-10-10 12:18:47,025] {taskinstance.py:1377} INFO - Starting attempt 2 of 2
[2023-10-10 12:18:47,025] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-10-10 12:18:47,040] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): extract_data_from_csv> on 2023-10-10 12:13:42.528919+00:00
[2023-10-10 12:18:47,049] {standard_task_runner.py:52} INFO - Started process 904 to run task
[2023-10-10 12:18:47,054] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_toll_data', 'extract_data_from_csv', 'manual__2023-10-10T12:13:42.528919+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/finalassignment/staging/ETL_toll_data.py', '--cfg-path', '/tmp/tmpjmk6i1bt', '--error-file', '/tmp/tmpce7u7t96']
[2023-10-10 12:18:47,055] {standard_task_runner.py:80} INFO - Job 6: Subtask extract_data_from_csv
[2023-10-10 12:18:47,154] {task_command.py:371} INFO - Running <TaskInstance: ETL_toll_data.extract_data_from_csv manual__2023-10-10T12:13:42.528919+00:00 [running]> on host 3812ee76f9ad
[2023-10-10 12:18:47,255] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ngocminhngo@mail.com
AIRFLOW_CTX_DAG_OWNER=ngocminhngo
AIRFLOW_CTX_DAG_ID=ETL_toll_data
AIRFLOW_CTX_TASK_ID=extract_data_from_csv
AIRFLOW_CTX_EXECUTION_DATE=2023-10-10T12:13:42.528919+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-10-10T12:13:42.528919+00:00
[2023-10-10 12:18:47,256] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-10-10 12:18:47,257] {subprocess.py:74} INFO - Running command: ['bash', '-c', "\n        cut -d ',' -f 1,2,3,4 /home/project/***/dags/finalassignment/vehicle-data.csv > /home/project/***/dags/finalassignment/csv_data.csv\n    "]
[2023-10-10 12:18:47,278] {subprocess.py:85} INFO - Output:
[2023-10-10 12:18:47,282] {subprocess.py:92} INFO - bash: line 2: /home/project/***/dags/finalassignment/csv_data.csv: Permission denied
[2023-10-10 12:18:47,283] {subprocess.py:96} INFO - Command exited with return code 1
[2023-10-10 12:18:47,306] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-10-10 12:18:47,311] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=ETL_toll_data, task_id=extract_data_from_csv, execution_date=20231010T121342, start_date=20231010T121847, end_date=20231010T121847
[2023-10-10 12:18:47,327] {standard_task_runner.py:97} ERROR - Failed to execute job 6 for task extract_data_from_csv (Bash command failed. The command returned a non-zero exit code 1.; 904)
[2023-10-10 12:18:47,345] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-10-10 12:18:47,447] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
